### ISSUE TITLE
Steps For running the server

### ISSUE THREAD

**Issue by jrashour1** [jrashour1/ct_java_attendence_server#2]
please add detail of required installations for running the java server

**Comment by Amrosamaelkomy** [comment]
install JDK 17
set JAVA_HOME=<path to jdk17> in your environment variables

run command in project directory
`./gradlew bootRun`

**Comment by Amrosamaelkomy** [comment]
or after installing JDK 17
run command in project directory 
`./gradlew bootRun -D org.gradle.java.home='path to jdk17'`
